#!/bin/bash

git clean -dxf
export LOCALLIB=$HOME/local-lib/Net-Works
export PERL5LIB=$LOCALLIB/lib/perl5:$LOCALLIB/lib/perl5/x86_64-linux

BINDIR=`mm-perl -MConfig -e 'print $Config{bin}'`

$BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB TAP::Harness::JUnit Math::BigInt::GMP

$BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB `$BINDIR/dzil authordeps`
$BINDIR/perl $BINDIR/cpanm -n -L $LOCALLIB `$BINDIR/dzil listdeps`

$BINDIR/perl $BINDIR/prove --harness=TAP::Harness::JUnit -lr -j 2 t
